In [1]:
import pandas as pd
import numpy as np
%matplotlib inline
import re

In [2]:
holidays_df = pd.read_csv('../Data/holidays_events.csv')

In [3]:
def replace_translation(translate):
    translate = re.sub("Traslado ","",translate)
    return(translate)

In [4]:
def event_replace(event):
    conv_string = event
    if "futbol" in event:
        conv_string = "Football"
    elif "Terremoto" in event:
        conv_string = "Earthquake"
    elif "Black Friday" in event:
        conv_string = "Tech Day"
    elif "Cyber Monday" in event:
        conv_string = "Tech Day"
    elif "Madre" in event:
        conv_string = "Mothers Day"
    elif "dia del ano" in event:
        conv_string = "New Years"
    elif "Navidad" in event:
        conv_string = "Christmas"
    elif "Difuntos" in event:
        conv_string = "Day of the Dead"
    elif "Independencia" in event:
        conv_string = "Independence Day"
    elif "Batalla de Pichincha" in event:
        conv_string = "Pichincha Battle"
    elif "Cantonizacion" in event:
        conv_string = "Cantonization Day"
    elif "Fundacion" in event:
        conv_string = "Foundation Day"
    elif "Provincializacion" in event:
        conv_string = "Provincialization Day"
    elif "Viernes Santo" in event:
        conv_string = "Good Friday"
    elif "Dia del Trabajo" in event:
        conv_string = "Workers Day"
    elif "Carnaval" in event:
        conv_string = "Carnival"
    return conv_string

In [5]:
holidays_df.head()

,date,type,locale,locale_name,description,transferred
0,2012-03-02,Holiday,Local,Manta,Fundacion de Manta,False
1,2012-04-01,Holiday,Regional,Cotopaxi,Provincializacion de Cotopaxi,False
2,2012-04-12,Holiday,Local,Cuenca,Fundacion de Cuenca,False
3,2012-04-14,Holiday,Local,Libertad,Cantonizacion de Libertad,False
4,2012-04-21,Holiday,Local,Riobamba,Cantonizacion de Riobamba,False

In [6]:
holidays_df['description'] = holidays_df['description'].apply(replace_translation)
holidays_df['description'] = holidays_df['description'].apply(event_replace)

In [7]:
holidays_df.groupby('description')['date'].count().reset_index().sort_values(by='date',ascending=False)

              description  date
6          Foundation Day    80
0       Cantonization Day    54
8        Independence Day    41
2               Christmas    40
4              Earthquake    31
12  Provincialization Day    24
10              New Years    15
5                Football    14
1                Carnival    10
9             Mothers Day    10
3         Day of the Dead     8
11       Pichincha Battle     7
13               Tech Day     6
7             Good Friday     5
14            Workers Day     5

In [8]:
holidays_df.loc[holidays_df["description"] == "Foundation Day", "description"] = 'District Holidays'
holidays_df.loc[holidays_df["description"] == "Cantonization Day", "description"] = 'District Holidays'
holidays_df.loc[holidays_df["description"] == "Provincialization Day", "description"] = 'District Holidays'
holidays_df.loc[holidays_df["description"] == "Christmas", "description"] = 'Common Holidays'
holidays_df.loc[holidays_df["description"] == "New Years", "description"] = 'Common Holidays'
holidays_df.loc[holidays_df["description"] == "Carnival", "description"] = 'Cultural Holidays'
holidays_df.loc[holidays_df["description"] == "Day of the Dead", "description"] = 'Cultural Holidays'
holidays_df.loc[holidays_df["description"] == "Pichincha Battle", "description"] = 'Cultural Holidays'
holidays_df.loc[holidays_df["description"] == "Football", "description"] = 'Cultural Holidays'
holidays_df.loc[holidays_df["description"] == "Mothers Day", "description"] = 'Others'
holidays_df.loc[holidays_df["description"] == "Tech Day", "description"] = 'Others'
holidays_df.loc[holidays_df["description"] == "Good Friday", "description"] = 'Others'
holidays_df.loc[holidays_df["description"] == "Workers Day", "description"] = 'Others'

In [9]:
holidays_df.groupby('description')['date'].count().reset_index().sort_values(by='date',ascending=False)

         description  date
2  District Holidays   158
0    Common Holidays    55
4   Independence Day    41
1  Cultural Holidays    39
3         Earthquake    31
5             Others    26

In [10]:
holidays_df.head()

         date     type    locale locale_name        description  transferred
0  2012-03-02  Holiday     Local       Manta  District Holidays        False
1  2012-04-01  Holiday  Regional    Cotopaxi  District Holidays        False
2  2012-04-12  Holiday     Local      Cuenca  District Holidays        False
3  2012-04-14  Holiday     Local    Libertad  District Holidays        False
4  2012-04-21  Holiday     Local    Riobamba  District Holidays        False